FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime
USER root

RUN mkdir -p /app
WORKDIR /app

COPY ./simple_tts_api.py /app/simple_tts_api.py
COPY ./scripts_simple_tts_api/requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

CMD ["python", "./simple_tts_api.py"]