FROM nvidia/cuda:11.6.1-devel-ubuntu20.04
USER root

# Install miniconda
RUN apt-get update && apt-get install \
libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 \
libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 curl -y
ENV CONDA_DIR /opt/conda
RUN curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 
# Put conda in path so we can use conda activate
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN conda --version
RUN conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia -y

RUN mkdir -p /app
WORKDIR /app

COPY ./simple_tts_api.py /app/simple_tts_api.py
COPY ./scripts_simple_tts_api/requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

CMD ["python", "./simple_tts_api.py"]