FROM artrajz/pytorch:1.13.1-cpu-py3.10.11-ubuntu22.04

RUN mkdir -p /app
WORKDIR /app

COPY ./scripts_simple_tts_api/requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

CMD ["echo", "Hello World"]